# FOLDERS
DATA_FOLDER = '.data'
VCF_BY_POPULATION_FOLDER = 'vcf_by_population'
FREQ_BY_POPULATION_FOLDER = 'freq_by_population'
SNPS_DATA_FOLDER = 'SNPs_data'
SAMPLES_FOLDER = f'{DATA_FOLDER}/samples'
VCF_BY_POPULATION_PATH = f'{DATA_FOLDER}/{VCF_BY_POPULATION_FOLDER}'
FREQ_BY_POPULATION_PATH = f'{DATA_FOLDER}/{FREQ_BY_POPULATION_FOLDER}'
SNPS_DATA_PATH = f'{DATA_FOLDER}/{SNPS_DATA_FOLDER}'
SNPS_DATA_FILE_NAME = 'snps_data_all.csv'

# FTP PATHS
FTP_PATH = 'ftp.1000genomes.ebi.ac.uk'
BASE_PATH = '/vol1/ftp/release/20130502/'

# DOCKER IMAGES
IMAGE_WORKDIR = '/usr/src/app/'
IMAGE_SHARE_FOLDER_PATH = f'{IMAGE_WORKDIR}share_folder'
VCF_TOOLS_IMAGE_NAME = 'avelior/vcftools'
PLINK2_IMAGE_NAME = 'avelior/plink2'
HG38DB_IMAGE_NAME = 'avelior/hg38db'

# VCF
MERGED_VCF_FILE_NAME = 'all_phase3.vcf'
MERGED_VCF_OUTPUT_PATH = f'{DATA_FOLDER}/{MERGED_VCF_FILE_NAME}'